python3 run.py \
	--data_dir $HOME/data/relations/NEREL/naa-docred-split \
	--transformer_type roberta \
	--model_name_or_path ai-forever/ruRoberta-large \
	--display_name ruroberta-inf \
	--load_path ./logs/nerel-ruroberta-ckpt/2025-09-26_00-47-57.793083 \
	--eval_mode single \
	--test_file test.json \
	--test_batch_size 1 \
	--num_labels 2 \
	--num_class 48 \
	--evi_thresh 0.2 \
	--max_seq_length 1460 \
	--max_sent_num 101