python3 run.py --do_train \
    --data_dir $HOME/data/relations/seccol-div-docred \
    --transformer_type bert \
    --model_name_or_path DeepPavlov/rubert-base-cased \
    --display_name seccol-test2 \
    --save_path ./logs/seccol-test2 \
    --train_file train.json \
    --dev_file test.json \
    --train_batch_size 16 \
    --test_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --num_labels 2 \
    --lr_transformer 3e-5 \
    --max_grad_norm 1.0 \
    --evi_thresh 0.2 \
    --evi_lambda 0.05 \
    --warmup_ratio 0.06 \
    --num_train_epochs 100 \
    --seed 42 \
    --num_class 7 \
    --max_seq_length 1500 \
    --max_sent_num 101 \
    --eval_mode single